#!/bin/bash

if [ -z "$1" ]; then
	echo "

  [ERROR]: missing arg, please specify what to run.
  Some examples:
      $./run example_01
      $./run web_cad

    "
	exit 1
fi

npm run serve -- --env="name=$1"
